FROM senyor/docker-node

RUN npm install -g babel babel-cli bower cross-env getstorybook grunt gulp lodash marked node-gyp npm-cli \
                   webpack webpack-dev-server html-webpack-plugin yarn \
                   gifsicle mozjpeg optipng-bin pngquant-bin ngrok